FastCode/Models/Dipendente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace FastCode.Models
{
    public class Dipendente
    {
        [Key]
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Matricola { get; set; }
        [ForeignKey("Dipendente")]
        public int? Manager { get; set; }
    }
}

FastCode/ViewModels/DipendenteView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FastCode.ViewModels
{
    public class DipendenteView
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Matricola { get; set; }
        public string Manager { get; set; }
    }
}

FastCode/Controllers/DipendentesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FastCode.Data;
using FastCode.Models;
using FastCode.ViewModels;

namespace FastCode.Controllers
{
    public class DipendentesController : Controller
    {
        private readonly FastCodeContext _context;

        public DipendentesController(FastCodeContext context)
        {
            _context = context;
        }

        private async Task<List<DipendenteView>> GetAllDipendenti()
        {
            var dipendenti = from dipendente in _context.Dipendente
                   join manager in _context.Dipendente on dipendente.Manager equals manager.Id into mann
                   from subman in mann.DefaultIfEmpty()
                   select new DipendenteView
                   {
                       Id = dipendente.Id,
                       Nome = dipendente.Nome,
                       Matricola = dipendente.Matricola,
                       Manager = subman.Nome ?? null
                   };

            return await dipendenti.ToListAsync();
        }

        // GET: Dipendentes
        public async Task<IActionResult> Index(string matricola)
        {

            if(string.IsNullOrEmpty(matricola))
            {
                return View(await GetAllDipendenti());
            }
            else
            {
                string cteQuery = @"
with cte as
(
  select Id, Nome, Matricola, Manager
  from   Dipendente
  where  Matricola = {0}

  union all

  select t.Id, t.Nome, t.Matricola, t.Manager
  from   cte c                                   
  inner join Dipendente t 
  on c.Manager = t.Id
)
select *
from cte where Manager is null";

                var cteDipendenti = _context.Dipendente.FromSqlRaw(cteQuery, matricola).AsEnumerable();

                if(cteDipendenti.Any())
                {
                    return View(cteDipendenti.Select(dipendente => new DipendenteView
                    {
                        Id = dipendente.Id,
                        Nome = dipendente.Nome,
                        Matricola = dipendente.Matricola,
                        Manager = null
                    }).ToList());
                }

                return View();
            }
        }

        // GET: Dipendentes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dipendenteTrova = from dipendente in _context.Dipendente
                join manager in _context.Dipendente on dipendente.Manager equals manager.Id into mann
                from subman in mann.DefaultIfEmpty()
                where dipendente.Id == id
                select new DipendenteView
                {
                    Id = dipendente.Id,
                    Nome = dipendente.Nome,
                    Matricola = dipendente.Matricola,
                    Manager = subman.Nome ?? null
                };

            var dipendenteTrovato = await dipendenteTrova.FirstOrDefaultAsync();

            if (dipendenteTrovato == null)
            {
                return NotFound();
            }

            return View(dipendenteTrovato);
        }

        // GET: Dipendentes/Create
        public async Task<IActionResult> Create()
        {
            var options = await _context.Dipendente.Select(a =>
                new SelectListItem
                {
                    Value = a.Id.ToString(),
                    Text = a.Nome
                }).ToListAsync();

            options.Add(new SelectListItem
            {
                Value = "",
                Text = "Vuoto"
            });

            var data = new Tuple<Dipendente, List<SelectListItem>> (new Dipendente(), options);

            return View(data);
        }

        // POST: Dipendentes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Matricola,Manager")] Dipendente dipendente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dipendente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dipendente);
        }

        // GET: Dipendentes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dipendente = await _context.Dipendente.FindAsync(id);
            if (dipendente == null)
            {
                return NotFound();
            }

            var options = await _context.Dipendente.Select(a =>
                new SelectListItem
                {
                    Value = a.Id.ToString(),
                    Text = a.Nome
                }).ToListAsync();

            options.Add(new SelectListItem
            {
                Value = "",
                Text = "Vuoto"
            });

            options = options.Select(
                l => new SelectListItem { 
                    Selected = (l.Value == id.ToString() || l.Value == ""), 
                    Text = l.Text, 
                    Value = l.Value }
            ).ToList();

            var data = new Tuple<Dipendente, List<SelectListItem>>(dipendente, options);

            return View(data);
        }

        // POST: Dipendentes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Matricola,Manager")] Dipendente dipendente)
        {
            if (id != dipendente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dipendente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DipendenteExists(dipendente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var options = await _context.Dipendente.Select(a =>
                new SelectListItem
                {
                    Value = a.Id.ToString(),
                    Text = a.Nome
                }).ToListAsync();

            options = options.Select(
                l => new SelectListItem { 
                    Selected = (l.Value == id.ToString()), 
                    Text = l.Text, 
                    Value = l.Value }
            ).ToList();

            var data = new Tuple<Dipendente, List<SelectListItem>>(dipendente, options);

            return View(data);
        }

        // GET: Dipendentes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dipendente = await _context.Dipendente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dipendente == null)
            {
                return NotFound();
            }

            return View(dipendente);
        }

        // POST: Dipendentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dipendente = await _context.Dipendente.FindAsync(id);
            _context.Dipendente.Remove(dipendente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DipendenteExists(int id)
        {
            return _context.Dipendente.Any(e => e.Id == id);
        }
    }
}

FastCode/Views/Dipendentes/Create.cshtml
@model Tuple<Dipendente, List<SelectListItem>>

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Dipendente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
		<form asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Item1.Nome" class="control-label"></label>
				<input name="Nome" asp-for="Item1.Nome" class="form-control" />
				<span asp-validation-for="Item1.Nome" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Item1.Matricola" class="control-label"></label>
				<input name="Matricola" asp-for="Item1.Matricola" class="form-control" />
				<span asp-validation-for="Item1.Matricola" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Item1.Manager" class="control-label"></label>
				<select name="Manager" asp-for="Item1.Manager" asp-items="Model.Item2"></select>
				<span asp-validation-for="Item1.Manager" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Create" class="btn btn-primary" />
			</div>
		</form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FastCode/Views/Dipendentes/Delete.cshtml
@model FastCode.Models.Dipendente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Dipendente</h4>
    <hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Nome)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Nome)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Matricola)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Matricola)
		</dd>
	</dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FastCode/Views/Dipendentes/Details.cshtml
@model FastCode.ViewModels.DipendenteView

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Dipendente</h4>
    <hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Nome)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Nome)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Matricola)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Matricola)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Manager)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Manager)
		</dd>
	</dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FastCode/Views/Dipendentes/Edit.cshtml
@model Tuple<Dipendente, List<SelectListItem>>

@{
	ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Dipendente</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" name="Id" asp-for="Item1.Id" />
			<div class="form-group">
				<label asp-for="Item1.Nome" class="control-label"></label>
				<input name="Nome" asp-for="Item1.Nome" class="form-control" />
				<span asp-validation-for="Item1.Nome" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Item1.Matricola" class="control-label"></label>
				<input name="Matricola" asp-for="Item1.Matricola" class="form-control" />
				<span asp-validation-for="Item1.Matricola" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Item1.Manager" class="control-label"></label>
				<select name="Manager" asp-for="Item1.Manager" asp-items="Model.Item2"></select>
				<span asp-validation-for="Item1.Manager" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FastCode/Views/Dipendentes/Index.cshtml
@model IEnumerable<FastCode.ViewModels.DipendenteView>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Dipendentes" asp-action="Index" method="get">
	<p>
		Inserisci matricola dipendente: <input type="text" name="Matricola" />
		<input type="submit" value="Seleziona Top Manager (1° Livello)" />
	</p>
</form>
<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Nome)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Matricola)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Manager)
			</th>
			<th></th>
		</tr>
	</thead>
	@if (Model != null)
	{
		<tbody>
			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.Nome)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Matricola)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Manager)
					</td>
					<td>
						<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
						<a asp-action="Details" asp-route-id="@item.Id">Details</a> |
						<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
					</td>
				</tr>
			}
		</tbody>
	}
</table>